# Generated by Django 4.2.4 on 2023-09-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.AddField(
            model_name='registration',
            name='blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
